### ISSUE TITLE
Training data availability

### ISSUE THREAD

**Issue by nuhash** [nv-tlabs/brushstroke_engine#3]
Hi,

Please can you make the training data available.

It is needed in order to run fair comparitive experiments and also validate the results in your paper. Since you released the trained models, there can't be any IP related issues.

Thanks

**Comment by shumash** [comment]
Thanks for your interest! We'll do our best to make it available by Monday. I'll post and update to the bug when it is up.

**Comment by shumash** [comment]
Hi! The data is now available on [our dataset website](https://research.nvidia.com/labs/toronto-ai/brushstroke_engine/astro_dataset.html). 

If you also require training scripts, please leave a comment on [this bug](https://github.com/nv-tlabs/brushstroke_engine/issues/4).
