### ISSUE TITLE
Brush_libs models generation

### ISSUE THREAD

**Issue by ruser-2020** [nv-tlabs/brushstroke_engine#7]
How can the following files be generated (available in your pretrained models, in the brush_libs folder)? 

_clip_brushes.pkl
clip_brushes.pkl.icons.zip
curated_zs.txt
curated_zs.txt.icons.zip
projected_artwork.pkl
projected_artwork.pkl.icons.zip
projected_novel_styles.pkl
projected_novel_styles.pkl.icons.zip
projected_training_styles.pkl
projected_training_styles.pkl.icons.zip
random5K_clarity0.9.txt
random5K_clarity0.9.txt.icons.zip_

**Comment by shumash** [comment]
Hi! Thank you for your interest in our project :) 

Brush optimization is described [here](https://github.com/nv-tlabs/brushstroke_engine#brush-optimization) in our README. 

1. Clip brushes were obtained using a script similar to the notebook: [scripts/optimize_clip.ipynb](https://github.com/nv-tlabs/brushstroke_engine/blob/main/scripts/optimize_clip.ipynb)
2. Curated z's were obtained manually as we browsed styles and found successful ones. 
3. Projected styles were obtained using [scripts/project_main.py](https://github.com/nv-tlabs/brushstroke_engine/blob/main/scripts/project_main.py), with one example in the README
4. Random styles were obtained by randomly sampling z's, then filtering out all styles with background clarity less than 0.9.

We hope this answers your question!
